
FROM ubuntu:20.04


ARG DEBIAN_FRONTEND=noninteractive

ENV PYTHONUNBUFFERED=1

RUN apt-get -y update \
    &&  apt-get -y install \
        software-properties-common \
        python3.12 \
        python3-pip --no-install-recommends \
    &&  add-apt-repository ppa:deadsnakes/ppa \
    &&  pip install fastapi==0.115.6 uvicorn==0.33.0 --no-cache-dir \
    &&  rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY ./ ./

EXPOSE 8000

CMD uvicorn app.main:app --host 0.0.0.0 --port $PORT
